/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *vbox1;
  GtkWidget *hbox1;
  GtkWidget *escape_key_label;
  GtkWidget *quit_help_label;
  GtkWidget *xoscope_help_label;
  GtkWidget *period_label;
  GtkWidget *enter_key_label;
  GtkWidget *refresh_help_label;
  GtkWidget *hbox2;
  GtkWidget *at_key_label;
  GtkWidget *load_help_label;
  GtkWidget *version_help_label;
  GtkWidget *min_max_label;
  GtkWidget *comma_key_label;
  GtkWidget *graticule_help_label;
  GtkWidget *hbox3;
  GtkWidget *pound_key_label;
  GtkWidget *save_help_label;
  GtkWidget *dash_key_label;
  GtkWidget *trigger_label;
  GtkWidget *plus_key_label;
  GtkWidget *fps_label;
  GtkWidget *period_key_label;
  GtkWidget *graticule_position_help_label;
  GtkWidget *hbox5;
  GtkWidget *ampersand_key_label;
  GtkWidget *data_source_label;
  GtkWidget *asterisk_key_label;
  GtkWidget *data_source_opt1_label;
  GtkWidget *trigger_source_label;
  GtkWidget *question_mark_label;
  GtkWidget *help_label;
  GtkWidget *hbox11;
  GtkWidget *exclaim_key_label;
  GtkWidget *line_style_label;
  GtkWidget *scroll_mode_label;
  GtkWidget *space_key_label;
  GtkWidget *run_stop_label;
  GtkWidget *hbox4;
  GtkWidget *vbox3;
  GtkWidget *Ch1_frame;
  GtkWidget *alignment1;
  GtkWidget *Ch1_vbox;
  GtkWidget *Ch1_label;
  GtkWidget *Ch1_scale_label;
  GtkWidget *Ch1_position_label;
  GtkWidget *Ch1_source_label;
  GtkWidget *Ch2_frame;
  GtkWidget *alignment2;
  GtkWidget *Ch2_vbox;
  GtkWidget *Ch2_label;
  GtkWidget *Ch2_scale_label;
  GtkWidget *Ch2_position_label;
  GtkWidget *Ch2_source_label;
  GtkWidget *Ch3_frame;
  GtkWidget *alignment3;
  GtkWidget *Ch3_vbox;
  GtkWidget *Ch3_label;
  GtkWidget *Ch3_scale_label;
  GtkWidget *Ch3_position_label;
  GtkWidget *Ch3_source_label;
  GtkWidget *Ch4_frame;
  GtkWidget *alignment4;
  GtkWidget *Ch4_vbox;
  GtkWidget *Ch4_label;
  GtkWidget *Ch4_scale_label;
  GtkWidget *Ch4_position_label;
  GtkWidget *Ch4_source_label;
  GtkWidget *databox_aspectframe;
  GtkWidget *databox_vbox;
  GtkWidget *databox_frame;
  GtkWidget *databox;
  GtkWidget *databox_hscrollbar;
  GtkWidget *vbox2;
  GtkWidget *Ch5_frame;
  GtkWidget *alignment5;
  GtkWidget *Ch5_vbox;
  GtkWidget *Ch5_label;
  GtkWidget *Ch5_scale_label;
  GtkWidget *Ch5_position_label;
  GtkWidget *Ch5_source_label;
  GtkWidget *Ch6_frame;
  GtkWidget *alignment6;
  GtkWidget *Ch6_vbox;
  GtkWidget *Ch6_label;
  GtkWidget *Ch6_scale_label;
  GtkWidget *Ch6_position_label;
  GtkWidget *Ch6_source_label;
  GtkWidget *Ch7_frame;
  GtkWidget *alignment7;
  GtkWidget *Ch7_vbox;
  GtkWidget *Ch7_label;
  GtkWidget *Ch7_scale_label;
  GtkWidget *Ch7_position_label;
  GtkWidget *Ch7_source_label;
  GtkWidget *Ch8_frame;
  GtkWidget *alignment8;
  GtkWidget *Ch8_vbox;
  GtkWidget *Ch8_label;
  GtkWidget *Ch8_scale_label;
  GtkWidget *Ch8_position_label;
  GtkWidget *Ch8_source_label;
  GtkWidget *hbox10;
  GtkWidget *vbox4;
  GtkWidget *hbox12;
  GtkWidget *tab_key_label;
  GtkWidget *tab_help_label;
  GtkWidget *hbox13;
  GtkWidget *left_brace_key_label;
  GtkWidget *scale_help_label;
  GtkWidget *right_brace_key_label;
  GtkWidget *hbox14;
  GtkWidget *left_bracket_key_label;
  GtkWidget *position_help_label;
  GtkWidget *right_bracket_key_label;
  GtkWidget *hbox15;
  GtkWidget *caret_key_label;
  GtkWidget *data_source_opt2_label;
  GtkWidget *vbox5;
  GtkWidget *hbox6;
  GtkWidget *status0_label;
  GtkWidget *_9_key_label;
  GtkWidget *timebase_label;
  GtkWidget *_0_key_label;
  GtkWidget *status1_label;
  GtkWidget *hbox7;
  GtkWidget *status2_label;
  GtkWidget *left_paren_key_label;
  GtkWidget *sample_rate_label;
  GtkWidget *right_paren_key_label;
  GtkWidget *status3_label;
  GtkWidget *hbox8;
  GtkWidget *status4_label;
  GtkWidget *samples_per_frame_label;
  GtkWidget *status5_label;
  GtkWidget *hbox9;
  GtkWidget *status6_label;
  GtkWidget *registers_left_key_label;
  GtkWidget *registers_label;
  GtkWidget *registers_right_key_label;
  GtkWidget *status7_label;
  GtkWidget *vbox6;
  GtkWidget *hbox18;
  GtkWidget *signal_key_label;
  GtkWidget *signal_help_label;
  GtkWidget *memory_help_label;
  GtkWidget *hbox16;
  GtkWidget *store_key_label;
  GtkWidget *store_help_label;
  GtkWidget *hbox17;
  GtkWidget *recall_key_label;
  GtkWidget *recall_help_label;

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (main_window, "main_window");
  gtk_window_set_title (GTK_WINDOW (main_window), _("xoscope"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_window), vbox1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 0);

  escape_key_label = gtk_label_new (_("(Esc)"));
  gtk_widget_set_name (escape_key_label, "escape_key_label");
  gtk_widget_show (escape_key_label);
  gtk_box_pack_start (GTK_BOX (hbox1), escape_key_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (escape_key_label), 1, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (escape_key_label), 5);

  quit_help_label = gtk_label_new (_("Quit"));
  gtk_widget_set_name (quit_help_label, "quit_help_label");
  gtk_widget_show (quit_help_label);
  gtk_box_pack_start (GTK_BOX (hbox1), quit_help_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (quit_help_label), 0, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (quit_help_label), 5);

  xoscope_help_label = gtk_label_new (_("xoscope"));
  gtk_widget_set_name (xoscope_help_label, "xoscope_help_label");
  gtk_widget_show (xoscope_help_label);
  gtk_box_pack_start (GTK_BOX (hbox1), xoscope_help_label, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (xoscope_help_label), 0, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (xoscope_help_label), 8);

  period_label = gtk_label_new (_("period"));
  gtk_widget_set_name (period_label, "period_label");
  gtk_widget_show (period_label);
  gtk_box_pack_start (GTK_BOX (hbox1), period_label, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (period_label), GTK_JUSTIFY_CENTER);

  enter_key_label = gtk_label_new (_("(Enter)"));
  gtk_widget_set_name (enter_key_label, "enter_key_label");
  gtk_widget_show (enter_key_label);
  gtk_box_pack_start (GTK_BOX (hbox1), enter_key_label, FALSE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (enter_key_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (enter_key_label), 1, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (enter_key_label), 6);

  refresh_help_label = gtk_label_new (_("Refresh"));
  gtk_widget_set_name (refresh_help_label, "refresh_help_label");
  gtk_widget_show (refresh_help_label);
  gtk_box_pack_start (GTK_BOX (hbox1), refresh_help_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (refresh_help_label), 0, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (refresh_help_label), 8);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, TRUE, 0);

  at_key_label = gtk_label_new (_("(@)"));
  gtk_widget_set_name (at_key_label, "at_key_label");
  gtk_widget_show (at_key_label);
  gtk_box_pack_start (GTK_BOX (hbox2), at_key_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (at_key_label), 1, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (at_key_label), 5);

  load_help_label = gtk_label_new (_("Load"));
  gtk_widget_set_name (load_help_label, "load_help_label");
  gtk_widget_show (load_help_label);
  gtk_box_pack_start (GTK_BOX (hbox2), load_help_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (load_help_label), 0, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (load_help_label), 5);

  version_help_label = gtk_label_new (_("ver: 2.0"));
  gtk_widget_set_name (version_help_label, "version_help_label");
  gtk_widget_show (version_help_label);
  gtk_box_pack_start (GTK_BOX (hbox2), version_help_label, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (version_help_label), 0, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (version_help_label), 8);

  min_max_label = gtk_label_new (_("min-max"));
  gtk_widget_set_name (min_max_label, "min_max_label");
  gtk_widget_show (min_max_label);
  gtk_box_pack_start (GTK_BOX (hbox2), min_max_label, TRUE, TRUE, 0);

  comma_key_label = gtk_label_new (_("(,)"));
  gtk_widget_set_name (comma_key_label, "comma_key_label");
  gtk_widget_show (comma_key_label);
  gtk_box_pack_start (GTK_BOX (hbox2), comma_key_label, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (comma_key_label), 1, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (comma_key_label), 6);

  graticule_help_label = gtk_label_new (_("Graticule"));
  gtk_widget_set_name (graticule_help_label, "graticule_help_label");
  gtk_widget_show (graticule_help_label);
  gtk_box_pack_start (GTK_BOX (hbox2), graticule_help_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (graticule_help_label), 0, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (graticule_help_label), 8);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, FALSE, TRUE, 0);

  pound_key_label = gtk_label_new (_("(#)"));
  gtk_widget_set_name (pound_key_label, "pound_key_label");
  gtk_widget_show (pound_key_label);
  gtk_box_pack_start (GTK_BOX (hbox3), pound_key_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (pound_key_label), 1, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (pound_key_label), 5);

  save_help_label = gtk_label_new (_("Save"));
  gtk_widget_set_name (save_help_label, "save_help_label");
  gtk_widget_show (save_help_label);
  gtk_box_pack_start (GTK_BOX (hbox3), save_help_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (save_help_label), 0, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (save_help_label), 15);

  dash_key_label = gtk_label_new (_("(_) (-)"));
  gtk_widget_set_name (dash_key_label, "dash_key_label");
  gtk_widget_show (dash_key_label);
  gtk_box_pack_start (GTK_BOX (hbox3), dash_key_label, FALSE, TRUE, 0);

  trigger_label = gtk_label_new (_("trigger"));
  gtk_widget_set_name (trigger_label, "trigger_label");
  gtk_widget_show (trigger_label);
  gtk_box_pack_start (GTK_BOX (hbox3), trigger_label, TRUE, TRUE, 0);

  plus_key_label = gtk_label_new (_("(=) (+)"));
  gtk_widget_set_name (plus_key_label, "plus_key_label");
  gtk_widget_show (plus_key_label);
  gtk_box_pack_start (GTK_BOX (hbox3), plus_key_label, FALSE, FALSE, 0);

  fps_label = gtk_label_new (_("fps"));
  gtk_widget_set_name (fps_label, "fps_label");
  gtk_widget_show (fps_label);
  gtk_box_pack_start (GTK_BOX (hbox3), fps_label, FALSE, TRUE, 0);
  gtk_label_set_width_chars (GTK_LABEL (fps_label), 10);

  period_key_label = gtk_label_new (_("(.)"));
  gtk_widget_set_name (period_key_label, "period_key_label");
  gtk_widget_show (period_key_label);
  gtk_box_pack_start (GTK_BOX (hbox3), period_key_label, FALSE, FALSE, 0);

  graticule_position_help_label = gtk_label_new (_("In Front"));
  gtk_widget_set_name (graticule_position_help_label, "graticule_position_help_label");
  gtk_widget_show (graticule_position_help_label);
  gtk_box_pack_start (GTK_BOX (hbox3), graticule_position_help_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (graticule_position_help_label), 0, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (graticule_position_help_label), 8);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox5, FALSE, TRUE, 0);

  ampersand_key_label = gtk_label_new (_("(&)"));
  gtk_widget_set_name (ampersand_key_label, "ampersand_key_label");
  gtk_widget_show (ampersand_key_label);
  gtk_box_pack_start (GTK_BOX (hbox5), ampersand_key_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (ampersand_key_label), 1, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (ampersand_key_label), 5);

  data_source_label = gtk_label_new (_("source"));
  gtk_widget_set_name (data_source_label, "data_source_label");
  gtk_widget_show (data_source_label);
  gtk_box_pack_start (GTK_BOX (hbox5), data_source_label, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (data_source_label), 0, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (data_source_label), 10);

  asterisk_key_label = gtk_label_new (_("(*)"));
  gtk_widget_set_name (asterisk_key_label, "asterisk_key_label");
  gtk_widget_show (asterisk_key_label);
  gtk_box_pack_start (GTK_BOX (hbox5), asterisk_key_label, FALSE, FALSE, 0);

  data_source_opt1_label = gtk_label_new (_("opt1"));
  gtk_widget_set_name (data_source_opt1_label, "data_source_opt1_label");
  gtk_widget_show (data_source_opt1_label);
  gtk_box_pack_start (GTK_BOX (hbox5), data_source_opt1_label, FALSE, FALSE, 0);

  trigger_source_label = gtk_label_new (_("trigger source"));
  gtk_widget_set_name (trigger_source_label, "trigger_source_label");
  gtk_widget_show (trigger_source_label);
  gtk_box_pack_start (GTK_BOX (hbox5), trigger_source_label, TRUE, TRUE, 0);

  question_mark_label = gtk_label_new (_("(?)"));
  gtk_widget_set_name (question_mark_label, "question_mark_label");
  gtk_widget_show (question_mark_label);
  gtk_box_pack_start (GTK_BOX (hbox5), question_mark_label, FALSE, FALSE, 0);

  help_label = gtk_label_new (_("Help"));
  gtk_widget_set_name (help_label, "help_label");
  gtk_widget_show (help_label);
  gtk_box_pack_start (GTK_BOX (hbox5), help_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (help_label), 0, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (help_label), 8);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox11, "hbox11");
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox11, FALSE, FALSE, 0);

  exclaim_key_label = gtk_label_new (_("(!)"));
  gtk_widget_set_name (exclaim_key_label, "exclaim_key_label");
  gtk_widget_show (exclaim_key_label);
  gtk_box_pack_start (GTK_BOX (hbox11), exclaim_key_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (exclaim_key_label), 1, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (exclaim_key_label), 13);

  line_style_label = gtk_label_new (_("line style"));
  gtk_widget_set_name (line_style_label, "line_style_label");
  gtk_widget_show (line_style_label);
  gtk_box_pack_start (GTK_BOX (hbox11), line_style_label, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (line_style_label), 0, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (line_style_label), 5);

  scroll_mode_label = gtk_label_new (_("scroll mode"));
  gtk_widget_set_name (scroll_mode_label, "scroll_mode_label");
  gtk_widget_show (scroll_mode_label);
  gtk_box_pack_start (GTK_BOX (hbox11), scroll_mode_label, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (scroll_mode_label), 0, 0.5);
  gtk_label_set_width_chars (GTK_LABEL (scroll_mode_label), 5);

  space_key_label = gtk_label_new (_("(space)"));
  gtk_widget_set_name (space_key_label, "space_key_label");
  gtk_widget_show (space_key_label);
  gtk_box_pack_start (GTK_BOX (hbox11), space_key_label, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (space_key_label), 1, 0.5);

  run_stop_label = gtk_label_new (_("run-stop"));
  gtk_widget_set_name (run_stop_label, "run_stop_label");
  gtk_widget_show (run_stop_label);
  gtk_box_pack_start (GTK_BOX (hbox11), run_stop_label, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (run_stop_label), 0, 0.5);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox4), 5);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox3, FALSE, TRUE, 0);

  Ch1_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (Ch1_frame, "Ch1_frame");
  gtk_widget_show (Ch1_frame);
  gtk_box_pack_start (GTK_BOX (vbox3), Ch1_frame, TRUE, TRUE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Ch1_frame), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  Ch1_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (Ch1_vbox, "Ch1_vbox");
  gtk_widget_show (Ch1_vbox);
  gtk_container_add (GTK_CONTAINER (alignment1), Ch1_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (Ch1_vbox), 3);

  Ch1_label = gtk_label_new (_("Channel 1"));
  gtk_widget_set_name (Ch1_label, "Ch1_label");
  gtk_widget_show (Ch1_label);
  gtk_box_pack_start (GTK_BOX (Ch1_vbox), Ch1_label, FALSE, FALSE, 0);

  Ch1_scale_label = gtk_label_new (_("Ch1_scale"));
  gtk_widget_set_name (Ch1_scale_label, "Ch1_scale_label");
  gtk_widget_show (Ch1_scale_label);
  gtk_box_pack_start (GTK_BOX (Ch1_vbox), Ch1_scale_label, FALSE, FALSE, 0);

  Ch1_position_label = gtk_label_new (_("Ch1_position"));
  gtk_widget_set_name (Ch1_position_label, "Ch1_position_label");
  gtk_widget_show (Ch1_position_label);
  gtk_box_pack_start (GTK_BOX (Ch1_vbox), Ch1_position_label, FALSE, FALSE, 0);

  Ch1_source_label = gtk_label_new (_("Ch1_source"));
  gtk_widget_set_name (Ch1_source_label, "Ch1_source_label");
  gtk_widget_show (Ch1_source_label);
  gtk_box_pack_start (GTK_BOX (Ch1_vbox), Ch1_source_label, FALSE, FALSE, 0);

  Ch2_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (Ch2_frame, "Ch2_frame");
  gtk_widget_show (Ch2_frame);
  gtk_box_pack_start (GTK_BOX (vbox3), Ch2_frame, TRUE, TRUE, 0);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (Ch2_frame), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 12, 0);

  Ch2_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (Ch2_vbox, "Ch2_vbox");
  gtk_widget_show (Ch2_vbox);
  gtk_container_add (GTK_CONTAINER (alignment2), Ch2_vbox);

  Ch2_label = gtk_label_new (_("Channel 2"));
  gtk_widget_set_name (Ch2_label, "Ch2_label");
  gtk_widget_show (Ch2_label);
  gtk_box_pack_start (GTK_BOX (Ch2_vbox), Ch2_label, FALSE, FALSE, 0);

  Ch2_scale_label = gtk_label_new (_("Ch2_scale"));
  gtk_widget_set_name (Ch2_scale_label, "Ch2_scale_label");
  gtk_widget_show (Ch2_scale_label);
  gtk_box_pack_start (GTK_BOX (Ch2_vbox), Ch2_scale_label, FALSE, FALSE, 0);

  Ch2_position_label = gtk_label_new (_("Ch2_position"));
  gtk_widget_set_name (Ch2_position_label, "Ch2_position_label");
  gtk_widget_show (Ch2_position_label);
  gtk_box_pack_start (GTK_BOX (Ch2_vbox), Ch2_position_label, FALSE, FALSE, 0);

  Ch2_source_label = gtk_label_new (_("Ch2_source"));
  gtk_widget_set_name (Ch2_source_label, "Ch2_source_label");
  gtk_widget_show (Ch2_source_label);
  gtk_box_pack_start (GTK_BOX (Ch2_vbox), Ch2_source_label, FALSE, FALSE, 0);

  Ch3_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (Ch3_frame, "Ch3_frame");
  gtk_widget_show (Ch3_frame);
  gtk_box_pack_start (GTK_BOX (vbox3), Ch3_frame, TRUE, TRUE, 0);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment3, "alignment3");
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (Ch3_frame), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 0, 0, 12, 0);

  Ch3_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (Ch3_vbox, "Ch3_vbox");
  gtk_widget_show (Ch3_vbox);
  gtk_container_add (GTK_CONTAINER (alignment3), Ch3_vbox);

  Ch3_label = gtk_label_new (_("Channel 3"));
  gtk_widget_set_name (Ch3_label, "Ch3_label");
  gtk_widget_show (Ch3_label);
  gtk_box_pack_start (GTK_BOX (Ch3_vbox), Ch3_label, FALSE, FALSE, 0);

  Ch3_scale_label = gtk_label_new (_("Ch3_scale"));
  gtk_widget_set_name (Ch3_scale_label, "Ch3_scale_label");
  gtk_widget_show (Ch3_scale_label);
  gtk_box_pack_start (GTK_BOX (Ch3_vbox), Ch3_scale_label, FALSE, FALSE, 0);

  Ch3_position_label = gtk_label_new (_("Ch3_position"));
  gtk_widget_set_name (Ch3_position_label, "Ch3_position_label");
  gtk_widget_show (Ch3_position_label);
  gtk_box_pack_start (GTK_BOX (Ch3_vbox), Ch3_position_label, FALSE, FALSE, 0);

  Ch3_source_label = gtk_label_new (_("Ch3_source"));
  gtk_widget_set_name (Ch3_source_label, "Ch3_source_label");
  gtk_widget_show (Ch3_source_label);
  gtk_box_pack_start (GTK_BOX (Ch3_vbox), Ch3_source_label, FALSE, FALSE, 0);

  Ch4_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (Ch4_frame, "Ch4_frame");
  gtk_widget_show (Ch4_frame);
  gtk_box_pack_start (GTK_BOX (vbox3), Ch4_frame, TRUE, TRUE, 0);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment4, "alignment4");
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (Ch4_frame), alignment4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment4), 0, 0, 12, 0);

  Ch4_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (Ch4_vbox, "Ch4_vbox");
  gtk_widget_show (Ch4_vbox);
  gtk_container_add (GTK_CONTAINER (alignment4), Ch4_vbox);

  Ch4_label = gtk_label_new (_("Channel 4"));
  gtk_widget_set_name (Ch4_label, "Ch4_label");
  gtk_widget_show (Ch4_label);
  gtk_box_pack_start (GTK_BOX (Ch4_vbox), Ch4_label, FALSE, FALSE, 0);

  Ch4_scale_label = gtk_label_new (_("Ch4_scale"));
  gtk_widget_set_name (Ch4_scale_label, "Ch4_scale_label");
  gtk_widget_show (Ch4_scale_label);
  gtk_box_pack_start (GTK_BOX (Ch4_vbox), Ch4_scale_label, FALSE, FALSE, 0);

  Ch4_position_label = gtk_label_new (_("Ch4_position"));
  gtk_widget_set_name (Ch4_position_label, "Ch4_position_label");
  gtk_widget_show (Ch4_position_label);
  gtk_box_pack_start (GTK_BOX (Ch4_vbox), Ch4_position_label, FALSE, FALSE, 0);

  Ch4_source_label = gtk_label_new (_("Ch4_source"));
  gtk_widget_set_name (Ch4_source_label, "Ch4_source_label");
  gtk_widget_show (Ch4_source_label);
  gtk_box_pack_start (GTK_BOX (Ch4_vbox), Ch4_source_label, FALSE, FALSE, 0);

  databox_aspectframe = gtk_aspect_frame_new (NULL, 0.5, 0.5, 1, FALSE);
  gtk_widget_set_name (databox_aspectframe, "databox_aspectframe");
  gtk_widget_show (databox_aspectframe);
  gtk_box_pack_start (GTK_BOX (hbox4), databox_aspectframe, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (databox_aspectframe), GTK_SHADOW_NONE);

  databox_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (databox_vbox, "databox_vbox");
  gtk_widget_show (databox_vbox);
  gtk_container_add (GTK_CONTAINER (databox_aspectframe), databox_vbox);

  databox_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (databox_frame, "databox_frame");
  gtk_widget_show (databox_frame);
  gtk_box_pack_start (GTK_BOX (databox_vbox), databox_frame, TRUE, TRUE, 0);

  databox = create_databox ("databox", "", "", 0, 0);
  gtk_widget_set_name (databox, "databox");
  gtk_widget_show (databox);
  gtk_container_add (GTK_CONTAINER (databox_frame), databox);
  GTK_WIDGET_UNSET_FLAGS (databox, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (databox, GTK_CAN_DEFAULT);

  databox_hscrollbar = gtk_hscrollbar_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 0, 0, 0, 0)));
  gtk_widget_set_name (databox_hscrollbar, "databox_hscrollbar");
  gtk_widget_show (databox_hscrollbar);
  gtk_box_pack_start (GTK_BOX (databox_vbox), databox_hscrollbar, FALSE, FALSE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox2, FALSE, TRUE, 0);

  Ch5_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (Ch5_frame, "Ch5_frame");
  gtk_widget_show (Ch5_frame);
  gtk_box_pack_start (GTK_BOX (vbox2), Ch5_frame, TRUE, TRUE, 0);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment5, "alignment5");
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (Ch5_frame), alignment5);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment5), 0, 0, 12, 0);

  Ch5_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (Ch5_vbox, "Ch5_vbox");
  gtk_widget_show (Ch5_vbox);
  gtk_container_add (GTK_CONTAINER (alignment5), Ch5_vbox);

  Ch5_label = gtk_label_new (_("Channel 5"));
  gtk_widget_set_name (Ch5_label, "Ch5_label");
  gtk_widget_show (Ch5_label);
  gtk_box_pack_start (GTK_BOX (Ch5_vbox), Ch5_label, FALSE, FALSE, 0);

  Ch5_scale_label = gtk_label_new (_("Ch5_scale"));
  gtk_widget_set_name (Ch5_scale_label, "Ch5_scale_label");
  gtk_widget_show (Ch5_scale_label);
  gtk_box_pack_start (GTK_BOX (Ch5_vbox), Ch5_scale_label, FALSE, FALSE, 0);

  Ch5_position_label = gtk_label_new (_("Ch5_position"));
  gtk_widget_set_name (Ch5_position_label, "Ch5_position_label");
  gtk_widget_show (Ch5_position_label);
  gtk_box_pack_start (GTK_BOX (Ch5_vbox), Ch5_position_label, FALSE, FALSE, 0);

  Ch5_source_label = gtk_label_new (_("Ch5_source"));
  gtk_widget_set_name (Ch5_source_label, "Ch5_source_label");
  gtk_widget_show (Ch5_source_label);
  gtk_box_pack_start (GTK_BOX (Ch5_vbox), Ch5_source_label, FALSE, FALSE, 0);

  Ch6_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (Ch6_frame, "Ch6_frame");
  gtk_widget_show (Ch6_frame);
  gtk_box_pack_start (GTK_BOX (vbox2), Ch6_frame, TRUE, TRUE, 0);

  alignment6 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment6, "alignment6");
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (Ch6_frame), alignment6);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment6), 0, 0, 12, 0);

  Ch6_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (Ch6_vbox, "Ch6_vbox");
  gtk_widget_show (Ch6_vbox);
  gtk_container_add (GTK_CONTAINER (alignment6), Ch6_vbox);

  Ch6_label = gtk_label_new (_("Channel 6"));
  gtk_widget_set_name (Ch6_label, "Ch6_label");
  gtk_widget_show (Ch6_label);
  gtk_box_pack_start (GTK_BOX (Ch6_vbox), Ch6_label, FALSE, FALSE, 0);

  Ch6_scale_label = gtk_label_new (_("Ch6_scale"));
  gtk_widget_set_name (Ch6_scale_label, "Ch6_scale_label");
  gtk_widget_show (Ch6_scale_label);
  gtk_box_pack_start (GTK_BOX (Ch6_vbox), Ch6_scale_label, FALSE, FALSE, 0);

  Ch6_position_label = gtk_label_new (_("Ch6_position"));
  gtk_widget_set_name (Ch6_position_label, "Ch6_position_label");
  gtk_widget_show (Ch6_position_label);
  gtk_box_pack_start (GTK_BOX (Ch6_vbox), Ch6_position_label, FALSE, FALSE, 0);

  Ch6_source_label = gtk_label_new (_("Ch6_source"));
  gtk_widget_set_name (Ch6_source_label, "Ch6_source_label");
  gtk_widget_show (Ch6_source_label);
  gtk_box_pack_start (GTK_BOX (Ch6_vbox), Ch6_source_label, FALSE, FALSE, 0);

  Ch7_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (Ch7_frame, "Ch7_frame");
  gtk_widget_show (Ch7_frame);
  gtk_box_pack_start (GTK_BOX (vbox2), Ch7_frame, TRUE, TRUE, 0);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment7, "alignment7");
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (Ch7_frame), alignment7);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment7), 0, 0, 12, 0);

  Ch7_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (Ch7_vbox, "Ch7_vbox");
  gtk_widget_show (Ch7_vbox);
  gtk_container_add (GTK_CONTAINER (alignment7), Ch7_vbox);

  Ch7_label = gtk_label_new (_("Channel 7"));
  gtk_widget_set_name (Ch7_label, "Ch7_label");
  gtk_widget_show (Ch7_label);
  gtk_box_pack_start (GTK_BOX (Ch7_vbox), Ch7_label, FALSE, FALSE, 0);

  Ch7_scale_label = gtk_label_new (_("Ch7_scale"));
  gtk_widget_set_name (Ch7_scale_label, "Ch7_scale_label");
  gtk_widget_show (Ch7_scale_label);
  gtk_box_pack_start (GTK_BOX (Ch7_vbox), Ch7_scale_label, FALSE, FALSE, 0);

  Ch7_position_label = gtk_label_new (_("Ch7_position"));
  gtk_widget_set_name (Ch7_position_label, "Ch7_position_label");
  gtk_widget_show (Ch7_position_label);
  gtk_box_pack_start (GTK_BOX (Ch7_vbox), Ch7_position_label, FALSE, FALSE, 0);

  Ch7_source_label = gtk_label_new (_("Ch7_source"));
  gtk_widget_set_name (Ch7_source_label, "Ch7_source_label");
  gtk_widget_show (Ch7_source_label);
  gtk_box_pack_start (GTK_BOX (Ch7_vbox), Ch7_source_label, FALSE, FALSE, 0);

  Ch8_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (Ch8_frame, "Ch8_frame");
  gtk_widget_show (Ch8_frame);
  gtk_box_pack_start (GTK_BOX (vbox2), Ch8_frame, TRUE, TRUE, 0);

  alignment8 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment8, "alignment8");
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (Ch8_frame), alignment8);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment8), 0, 0, 12, 0);

  Ch8_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (Ch8_vbox, "Ch8_vbox");
  gtk_widget_show (Ch8_vbox);
  gtk_container_add (GTK_CONTAINER (alignment8), Ch8_vbox);

  Ch8_label = gtk_label_new (_("Channel 8"));
  gtk_widget_set_name (Ch8_label, "Ch8_label");
  gtk_widget_show (Ch8_label);
  gtk_box_pack_start (GTK_BOX (Ch8_vbox), Ch8_label, FALSE, FALSE, 0);

  Ch8_scale_label = gtk_label_new (_("Ch8_scale"));
  gtk_widget_set_name (Ch8_scale_label, "Ch8_scale_label");
  gtk_widget_show (Ch8_scale_label);
  gtk_box_pack_start (GTK_BOX (Ch8_vbox), Ch8_scale_label, FALSE, FALSE, 0);

  Ch8_position_label = gtk_label_new (_("Ch8_position"));
  gtk_widget_set_name (Ch8_position_label, "Ch8_position_label");
  gtk_widget_show (Ch8_position_label);
  gtk_box_pack_start (GTK_BOX (Ch8_vbox), Ch8_position_label, FALSE, FALSE, 0);

  Ch8_source_label = gtk_label_new (_("Ch8_source"));
  gtk_widget_set_name (Ch8_source_label, "Ch8_source_label");
  gtk_widget_show (Ch8_source_label);
  gtk_box_pack_start (GTK_BOX (Ch8_vbox), Ch8_source_label, FALSE, FALSE, 0);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox10, "hbox10");
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox10, FALSE, FALSE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox10), vbox4, FALSE, TRUE, 0);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox12, "hbox12");
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox12, FALSE, TRUE, 0);

  tab_key_label = gtk_label_new (_("(Tab)"));
  gtk_widget_set_name (tab_key_label, "tab_key_label");
  gtk_widget_show (tab_key_label);
  gtk_box_pack_start (GTK_BOX (hbox12), tab_key_label, FALSE, FALSE, 0);

  tab_help_label = gtk_label_new (_("Visible"));
  gtk_widget_set_name (tab_help_label, "tab_help_label");
  gtk_widget_show (tab_help_label);
  gtk_box_pack_start (GTK_BOX (hbox12), tab_help_label, FALSE, FALSE, 0);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox13, "hbox13");
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox13, FALSE, FALSE, 0);

  left_brace_key_label = gtk_label_new (_("({)"));
  gtk_widget_set_name (left_brace_key_label, "left_brace_key_label");
  gtk_widget_show (left_brace_key_label);
  gtk_box_pack_start (GTK_BOX (hbox13), left_brace_key_label, FALSE, FALSE, 0);

  scale_help_label = gtk_label_new (_("Scale"));
  gtk_widget_set_name (scale_help_label, "scale_help_label");
  gtk_widget_show (scale_help_label);
  gtk_box_pack_start (GTK_BOX (hbox13), scale_help_label, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (scale_help_label), TRUE);

  right_brace_key_label = gtk_label_new (_("(})"));
  gtk_widget_set_name (right_brace_key_label, "right_brace_key_label");
  gtk_widget_show (right_brace_key_label);
  gtk_box_pack_start (GTK_BOX (hbox13), right_brace_key_label, FALSE, FALSE, 0);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox14, "hbox14");
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox14, FALSE, FALSE, 0);

  left_bracket_key_label = gtk_label_new (_("([)"));
  gtk_widget_set_name (left_bracket_key_label, "left_bracket_key_label");
  gtk_widget_show (left_bracket_key_label);
  gtk_box_pack_start (GTK_BOX (hbox14), left_bracket_key_label, FALSE, FALSE, 0);

  position_help_label = gtk_label_new (_("Pos."));
  gtk_widget_set_name (position_help_label, "position_help_label");
  gtk_widget_show (position_help_label);
  gtk_box_pack_start (GTK_BOX (hbox14), position_help_label, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (position_help_label), TRUE);

  right_bracket_key_label = gtk_label_new (_("(])"));
  gtk_widget_set_name (right_bracket_key_label, "right_bracket_key_label");
  gtk_widget_show (right_bracket_key_label);
  gtk_box_pack_start (GTK_BOX (hbox14), right_bracket_key_label, FALSE, FALSE, 0);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox15, "hbox15");
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox15, FALSE, FALSE, 0);

  caret_key_label = gtk_label_new (_("(^)"));
  gtk_widget_set_name (caret_key_label, "caret_key_label");
  gtk_widget_show (caret_key_label);
  gtk_box_pack_start (GTK_BOX (hbox15), caret_key_label, FALSE, FALSE, 0);

  data_source_opt2_label = gtk_label_new (_("opt2"));
  gtk_widget_set_name (data_source_opt2_label, "data_source_opt2_label");
  gtk_widget_show (data_source_opt2_label);
  gtk_box_pack_start (GTK_BOX (hbox15), data_source_opt2_label, FALSE, TRUE, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox10), vbox5, TRUE, TRUE, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox6, "hbox6");
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox6, FALSE, TRUE, 0);

  status0_label = gtk_label_new (_("status 0"));
  gtk_widget_set_name (status0_label, "status0_label");
  gtk_widget_show (status0_label);
  gtk_box_pack_start (GTK_BOX (hbox6), status0_label, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (status0_label), 0, 0.5);

  _9_key_label = gtk_label_new (_("(9)"));
  gtk_widget_set_name (_9_key_label, "_9_key_label");
  gtk_widget_show (_9_key_label);
  gtk_box_pack_start (GTK_BOX (hbox6), _9_key_label, FALSE, FALSE, 0);

  timebase_label = gtk_label_new (_("timebase"));
  gtk_widget_set_name (timebase_label, "timebase_label");
  gtk_widget_show (timebase_label);
  gtk_box_pack_start (GTK_BOX (hbox6), timebase_label, FALSE, TRUE, 0);
  gtk_label_set_width_chars (GTK_LABEL (timebase_label), 10);

  _0_key_label = gtk_label_new (_("(0)"));
  gtk_widget_set_name (_0_key_label, "_0_key_label");
  gtk_widget_show (_0_key_label);
  gtk_box_pack_start (GTK_BOX (hbox6), _0_key_label, FALSE, FALSE, 0);

  status1_label = gtk_label_new (_("status 1"));
  gtk_widget_set_name (status1_label, "status1_label");
  gtk_widget_show (status1_label);
  gtk_box_pack_start (GTK_BOX (hbox6), status1_label, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (status1_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (status1_label), 1, 0.5);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox7, "hbox7");
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox7, FALSE, TRUE, 0);

  status2_label = gtk_label_new (_("status 2"));
  gtk_widget_set_name (status2_label, "status2_label");
  gtk_widget_show (status2_label);
  gtk_box_pack_start (GTK_BOX (hbox7), status2_label, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (status2_label), 0, 0.5);

  left_paren_key_label = gtk_label_new (_("(()"));
  gtk_widget_set_name (left_paren_key_label, "left_paren_key_label");
  gtk_widget_show (left_paren_key_label);
  gtk_box_pack_start (GTK_BOX (hbox7), left_paren_key_label, FALSE, FALSE, 0);

  sample_rate_label = gtk_label_new (_("sample rate"));
  gtk_widget_set_name (sample_rate_label, "sample_rate_label");
  gtk_widget_show (sample_rate_label);
  gtk_box_pack_start (GTK_BOX (hbox7), sample_rate_label, FALSE, TRUE, 0);

  right_paren_key_label = gtk_label_new (_("())"));
  gtk_widget_set_name (right_paren_key_label, "right_paren_key_label");
  gtk_widget_show (right_paren_key_label);
  gtk_box_pack_start (GTK_BOX (hbox7), right_paren_key_label, FALSE, FALSE, 0);

  status3_label = gtk_label_new (_("status 3"));
  gtk_widget_set_name (status3_label, "status3_label");
  gtk_widget_show (status3_label);
  gtk_box_pack_start (GTK_BOX (hbox7), status3_label, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (status3_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (status3_label), 1, 0.5);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox8, "hbox8");
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox8, FALSE, TRUE, 0);

  status4_label = gtk_label_new (_("status 4"));
  gtk_widget_set_name (status4_label, "status4_label");
  gtk_widget_show (status4_label);
  gtk_box_pack_start (GTK_BOX (hbox8), status4_label, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (status4_label), 0, 0.5);

  samples_per_frame_label = gtk_label_new (_("samples per frame"));
  gtk_widget_set_name (samples_per_frame_label, "samples_per_frame_label");
  gtk_widget_show (samples_per_frame_label);
  gtk_box_pack_start (GTK_BOX (hbox8), samples_per_frame_label, FALSE, TRUE, 0);

  status5_label = gtk_label_new (_("status 5"));
  gtk_widget_set_name (status5_label, "status5_label");
  gtk_widget_show (status5_label);
  gtk_box_pack_start (GTK_BOX (hbox8), status5_label, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (status5_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (status5_label), 1, 0.5);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox9, "hbox9");
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox9, FALSE, TRUE, 0);

  status6_label = gtk_label_new (_("status 6"));
  gtk_widget_set_name (status6_label, "status6_label");
  gtk_widget_show (status6_label);
  gtk_box_pack_start (GTK_BOX (hbox9), status6_label, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (status6_label), 0, 0.5);

  registers_left_key_label = gtk_label_new (_("("));
  gtk_widget_set_name (registers_left_key_label, "registers_left_key_label");
  gtk_widget_show (registers_left_key_label);
  gtk_box_pack_start (GTK_BOX (hbox9), registers_left_key_label, FALSE, FALSE, 0);

  registers_label = gtk_label_new (_("registers"));
  gtk_widget_set_name (registers_label, "registers_label");
  gtk_widget_show (registers_label);
  gtk_box_pack_start (GTK_BOX (hbox9), registers_label, FALSE, TRUE, 0);

  registers_right_key_label = gtk_label_new (_(")"));
  gtk_widget_set_name (registers_right_key_label, "registers_right_key_label");
  gtk_widget_show (registers_right_key_label);
  gtk_box_pack_start (GTK_BOX (hbox9), registers_right_key_label, FALSE, FALSE, 0);

  status7_label = gtk_label_new (_("status 7"));
  gtk_widget_set_name (status7_label, "status7_label");
  gtk_widget_show (status7_label);
  gtk_box_pack_start (GTK_BOX (hbox9), status7_label, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (status7_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (status7_label), 1, 0.5);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox6, "vbox6");
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (hbox10), vbox6, FALSE, TRUE, 0);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox18, "hbox18");
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox18, FALSE, FALSE, 0);

  signal_key_label = gtk_label_new (_("(a-b)"));
  gtk_widget_set_name (signal_key_label, "signal_key_label");
  gtk_widget_show (signal_key_label);
  gtk_box_pack_start (GTK_BOX (hbox18), signal_key_label, FALSE, FALSE, 0);

  signal_help_label = gtk_label_new (_("Signal"));
  gtk_widget_set_name (signal_help_label, "signal_help_label");
  gtk_widget_show (signal_help_label);
  gtk_box_pack_start (GTK_BOX (hbox18), signal_help_label, FALSE, FALSE, 0);

  memory_help_label = gtk_label_new (_("Memory"));
  gtk_widget_set_name (memory_help_label, "memory_help_label");
  gtk_widget_show (memory_help_label);
  gtk_box_pack_start (GTK_BOX (vbox6), memory_help_label, FALSE, FALSE, 0);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox16, "hbox16");
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox16, FALSE, FALSE, 0);

  store_key_label = gtk_label_new (_("(A-W)"));
  gtk_widget_set_name (store_key_label, "store_key_label");
  gtk_widget_show (store_key_label);
  gtk_box_pack_start (GTK_BOX (hbox16), store_key_label, FALSE, FALSE, 0);

  store_help_label = gtk_label_new (_("Store"));
  gtk_widget_set_name (store_help_label, "store_help_label");
  gtk_widget_show (store_help_label);
  gtk_box_pack_start (GTK_BOX (hbox16), store_help_label, FALSE, FALSE, 0);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox17, "hbox17");
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox17, FALSE, FALSE, 0);

  recall_key_label = gtk_label_new (_("(a-z)"));
  gtk_widget_set_name (recall_key_label, "recall_key_label");
  gtk_widget_show (recall_key_label);
  gtk_box_pack_start (GTK_BOX (hbox17), recall_key_label, FALSE, FALSE, 0);

  recall_help_label = gtk_label_new (_("Recall"));
  gtk_widget_set_name (recall_help_label, "recall_help_label");
  gtk_widget_show (recall_help_label);
  gtk_box_pack_start (GTK_BOX (hbox17), recall_help_label, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) main_window, "key_press_event",
                    G_CALLBACK (key_press_event),
                    NULL);
  g_signal_connect ((gpointer) main_window, "delete_event",
                    G_CALLBACK (delete_event),
                    NULL);
  g_signal_connect ((gpointer) databox, "button_press_event",
                    G_CALLBACK (on_databox_button_press_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (main_window, escape_key_label, "escape_key_label");
  GLADE_HOOKUP_OBJECT (main_window, quit_help_label, "quit_help_label");
  GLADE_HOOKUP_OBJECT (main_window, xoscope_help_label, "xoscope_help_label");
  GLADE_HOOKUP_OBJECT (main_window, period_label, "period_label");
  GLADE_HOOKUP_OBJECT (main_window, enter_key_label, "enter_key_label");
  GLADE_HOOKUP_OBJECT (main_window, refresh_help_label, "refresh_help_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (main_window, at_key_label, "at_key_label");
  GLADE_HOOKUP_OBJECT (main_window, load_help_label, "load_help_label");
  GLADE_HOOKUP_OBJECT (main_window, version_help_label, "version_help_label");
  GLADE_HOOKUP_OBJECT (main_window, min_max_label, "min_max_label");
  GLADE_HOOKUP_OBJECT (main_window, comma_key_label, "comma_key_label");
  GLADE_HOOKUP_OBJECT (main_window, graticule_help_label, "graticule_help_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (main_window, pound_key_label, "pound_key_label");
  GLADE_HOOKUP_OBJECT (main_window, save_help_label, "save_help_label");
  GLADE_HOOKUP_OBJECT (main_window, dash_key_label, "dash_key_label");
  GLADE_HOOKUP_OBJECT (main_window, trigger_label, "trigger_label");
  GLADE_HOOKUP_OBJECT (main_window, plus_key_label, "plus_key_label");
  GLADE_HOOKUP_OBJECT (main_window, fps_label, "fps_label");
  GLADE_HOOKUP_OBJECT (main_window, period_key_label, "period_key_label");
  GLADE_HOOKUP_OBJECT (main_window, graticule_position_help_label, "graticule_position_help_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (main_window, ampersand_key_label, "ampersand_key_label");
  GLADE_HOOKUP_OBJECT (main_window, data_source_label, "data_source_label");
  GLADE_HOOKUP_OBJECT (main_window, asterisk_key_label, "asterisk_key_label");
  GLADE_HOOKUP_OBJECT (main_window, data_source_opt1_label, "data_source_opt1_label");
  GLADE_HOOKUP_OBJECT (main_window, trigger_source_label, "trigger_source_label");
  GLADE_HOOKUP_OBJECT (main_window, question_mark_label, "question_mark_label");
  GLADE_HOOKUP_OBJECT (main_window, help_label, "help_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (main_window, exclaim_key_label, "exclaim_key_label");
  GLADE_HOOKUP_OBJECT (main_window, line_style_label, "line_style_label");
  GLADE_HOOKUP_OBJECT (main_window, scroll_mode_label, "scroll_mode_label");
  GLADE_HOOKUP_OBJECT (main_window, space_key_label, "space_key_label");
  GLADE_HOOKUP_OBJECT (main_window, run_stop_label, "run_stop_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (main_window, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (main_window, Ch1_frame, "Ch1_frame");
  GLADE_HOOKUP_OBJECT (main_window, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (main_window, Ch1_vbox, "Ch1_vbox");
  GLADE_HOOKUP_OBJECT (main_window, Ch1_label, "Ch1_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch1_scale_label, "Ch1_scale_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch1_position_label, "Ch1_position_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch1_source_label, "Ch1_source_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch2_frame, "Ch2_frame");
  GLADE_HOOKUP_OBJECT (main_window, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (main_window, Ch2_vbox, "Ch2_vbox");
  GLADE_HOOKUP_OBJECT (main_window, Ch2_label, "Ch2_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch2_scale_label, "Ch2_scale_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch2_position_label, "Ch2_position_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch2_source_label, "Ch2_source_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch3_frame, "Ch3_frame");
  GLADE_HOOKUP_OBJECT (main_window, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (main_window, Ch3_vbox, "Ch3_vbox");
  GLADE_HOOKUP_OBJECT (main_window, Ch3_label, "Ch3_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch3_scale_label, "Ch3_scale_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch3_position_label, "Ch3_position_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch3_source_label, "Ch3_source_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch4_frame, "Ch4_frame");
  GLADE_HOOKUP_OBJECT (main_window, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (main_window, Ch4_vbox, "Ch4_vbox");
  GLADE_HOOKUP_OBJECT (main_window, Ch4_label, "Ch4_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch4_scale_label, "Ch4_scale_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch4_position_label, "Ch4_position_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch4_source_label, "Ch4_source_label");
  GLADE_HOOKUP_OBJECT (main_window, databox_aspectframe, "databox_aspectframe");
  GLADE_HOOKUP_OBJECT (main_window, databox_vbox, "databox_vbox");
  GLADE_HOOKUP_OBJECT (main_window, databox_frame, "databox_frame");
  GLADE_HOOKUP_OBJECT (main_window, databox, "databox");
  GLADE_HOOKUP_OBJECT (main_window, databox_hscrollbar, "databox_hscrollbar");
  GLADE_HOOKUP_OBJECT (main_window, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (main_window, Ch5_frame, "Ch5_frame");
  GLADE_HOOKUP_OBJECT (main_window, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (main_window, Ch5_vbox, "Ch5_vbox");
  GLADE_HOOKUP_OBJECT (main_window, Ch5_label, "Ch5_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch5_scale_label, "Ch5_scale_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch5_position_label, "Ch5_position_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch5_source_label, "Ch5_source_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch6_frame, "Ch6_frame");
  GLADE_HOOKUP_OBJECT (main_window, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (main_window, Ch6_vbox, "Ch6_vbox");
  GLADE_HOOKUP_OBJECT (main_window, Ch6_label, "Ch6_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch6_scale_label, "Ch6_scale_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch6_position_label, "Ch6_position_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch6_source_label, "Ch6_source_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch7_frame, "Ch7_frame");
  GLADE_HOOKUP_OBJECT (main_window, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (main_window, Ch7_vbox, "Ch7_vbox");
  GLADE_HOOKUP_OBJECT (main_window, Ch7_label, "Ch7_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch7_scale_label, "Ch7_scale_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch7_position_label, "Ch7_position_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch7_source_label, "Ch7_source_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch8_frame, "Ch8_frame");
  GLADE_HOOKUP_OBJECT (main_window, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (main_window, Ch8_vbox, "Ch8_vbox");
  GLADE_HOOKUP_OBJECT (main_window, Ch8_label, "Ch8_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch8_scale_label, "Ch8_scale_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch8_position_label, "Ch8_position_label");
  GLADE_HOOKUP_OBJECT (main_window, Ch8_source_label, "Ch8_source_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (main_window, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (main_window, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (main_window, tab_key_label, "tab_key_label");
  GLADE_HOOKUP_OBJECT (main_window, tab_help_label, "tab_help_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (main_window, left_brace_key_label, "left_brace_key_label");
  GLADE_HOOKUP_OBJECT (main_window, scale_help_label, "scale_help_label");
  GLADE_HOOKUP_OBJECT (main_window, right_brace_key_label, "right_brace_key_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (main_window, left_bracket_key_label, "left_bracket_key_label");
  GLADE_HOOKUP_OBJECT (main_window, position_help_label, "position_help_label");
  GLADE_HOOKUP_OBJECT (main_window, right_bracket_key_label, "right_bracket_key_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (main_window, caret_key_label, "caret_key_label");
  GLADE_HOOKUP_OBJECT (main_window, data_source_opt2_label, "data_source_opt2_label");
  GLADE_HOOKUP_OBJECT (main_window, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (main_window, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (main_window, status0_label, "status0_label");
  GLADE_HOOKUP_OBJECT (main_window, _9_key_label, "_9_key_label");
  GLADE_HOOKUP_OBJECT (main_window, timebase_label, "timebase_label");
  GLADE_HOOKUP_OBJECT (main_window, _0_key_label, "_0_key_label");
  GLADE_HOOKUP_OBJECT (main_window, status1_label, "status1_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (main_window, status2_label, "status2_label");
  GLADE_HOOKUP_OBJECT (main_window, left_paren_key_label, "left_paren_key_label");
  GLADE_HOOKUP_OBJECT (main_window, sample_rate_label, "sample_rate_label");
  GLADE_HOOKUP_OBJECT (main_window, right_paren_key_label, "right_paren_key_label");
  GLADE_HOOKUP_OBJECT (main_window, status3_label, "status3_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (main_window, status4_label, "status4_label");
  GLADE_HOOKUP_OBJECT (main_window, samples_per_frame_label, "samples_per_frame_label");
  GLADE_HOOKUP_OBJECT (main_window, status5_label, "status5_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (main_window, status6_label, "status6_label");
  GLADE_HOOKUP_OBJECT (main_window, registers_left_key_label, "registers_left_key_label");
  GLADE_HOOKUP_OBJECT (main_window, registers_label, "registers_label");
  GLADE_HOOKUP_OBJECT (main_window, registers_right_key_label, "registers_right_key_label");
  GLADE_HOOKUP_OBJECT (main_window, status7_label, "status7_label");
  GLADE_HOOKUP_OBJECT (main_window, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (main_window, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (main_window, signal_key_label, "signal_key_label");
  GLADE_HOOKUP_OBJECT (main_window, signal_help_label, "signal_help_label");
  GLADE_HOOKUP_OBJECT (main_window, memory_help_label, "memory_help_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (main_window, store_key_label, "store_key_label");
  GLADE_HOOKUP_OBJECT (main_window, store_help_label, "store_help_label");
  GLADE_HOOKUP_OBJECT (main_window, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (main_window, recall_key_label, "recall_key_label");
  GLADE_HOOKUP_OBJECT (main_window, recall_help_label, "recall_help_label");

  return main_window;
}

GtkWidget*
create_comedi_dialog (void)
{
  GtkWidget *comedi_dialog;
  GtkWidget *dialog_vbox3;
  GtkWidget *notebook2;
  GtkWidget *option_table;
  GtkWidget *device_label;
  GtkWidget *label26;
  GtkWidget *device_entry;
  GtkWidget *subdevice_optionmenu;
  GtkWidget *convertwidget1;
  GtkWidget *label28;
  GtkWidget *rate_entry;
  GtkWidget *label27;
  GtkWidget *hbox7;
  GtkWidget *aref_ground;
  GSList *aref_ground_group = NULL;
  GtkWidget *aref_diff;
  GtkWidget *aref_common;
  GtkWidget *label29;
  GtkWidget *hbox8;
  GtkWidget *bufsize_default;
  GSList *bufsize_default_group = NULL;
  GtkWidget *bufsize_custom;
  GtkWidget *bufsize_entry;
  GtkWidget *label30;
  GtkWidget *empty_notebook_page;
  GtkWidget *label31;
  GtkWidget *dialog_action_area3;
  GtkWidget *hbuttonbox2;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *button9;

  comedi_dialog = gtk_dialog_new ();
  gtk_widget_set_name (comedi_dialog, "comedi_dialog");
  gtk_window_set_title (GTK_WINDOW (comedi_dialog), _("COMEDI Options"));
  gtk_window_set_type_hint (GTK_WINDOW (comedi_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (comedi_dialog)->vbox;
  gtk_widget_set_name (dialog_vbox3, "dialog_vbox3");
  gtk_widget_show (dialog_vbox3);

  notebook2 = gtk_notebook_new ();
  gtk_widget_set_name (notebook2, "notebook2");
  gtk_widget_show (notebook2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), notebook2, TRUE, TRUE, 0);

  option_table = gtk_table_new (5, 2, FALSE);
  gtk_widget_set_name (option_table, "option_table");
  gtk_widget_show (option_table);
  gtk_container_add (GTK_CONTAINER (notebook2), option_table);
  gtk_container_set_border_width (GTK_CONTAINER (option_table), 10);
  gtk_table_set_row_spacings (GTK_TABLE (option_table), 10);
  gtk_table_set_col_spacings (GTK_TABLE (option_table), 10);

  device_label = gtk_label_new (_("Device:"));
  gtk_widget_set_name (device_label, "device_label");
  gtk_widget_show (device_label);
  gtk_table_attach (GTK_TABLE (option_table), device_label, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (device_label), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (device_label), 0, 0.5);

  label26 = gtk_label_new (_("Subdevice:"));
  gtk_widget_set_name (label26, "label26");
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (option_table), label26, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label26), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  device_entry = gtk_entry_new ();
  gtk_widget_set_name (device_entry, "device_entry");
  gtk_widget_show (device_entry);
  gtk_table_attach (GTK_TABLE (option_table), device_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  subdevice_optionmenu = gtk_option_menu_new ();
  gtk_widget_set_name (subdevice_optionmenu, "subdevice_optionmenu");
  gtk_widget_show (subdevice_optionmenu);
  gtk_table_attach (GTK_TABLE (option_table), subdevice_optionmenu, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  convertwidget1 = gtk_menu_new ();
  gtk_widget_set_name (convertwidget1, "convertwidget1");

  gtk_option_menu_set_menu (GTK_OPTION_MENU (subdevice_optionmenu), convertwidget1);

  label28 = gtk_label_new (_("Sampling rate (Hz):"));
  gtk_widget_set_name (label28, "label28");
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (option_table), label28, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label28), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  rate_entry = gtk_entry_new ();
  gtk_widget_set_name (rate_entry, "rate_entry");
  gtk_widget_show (rate_entry);
  gtk_table_attach (GTK_TABLE (option_table), rate_entry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (0), 0, 0);

  label27 = gtk_label_new (_("Analog reference:"));
  gtk_widget_set_name (label27, "label27");
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (option_table), label27, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label27), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox7, "hbox7");
  gtk_widget_show (hbox7);
  gtk_table_attach (GTK_TABLE (option_table), hbox7, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  aref_ground = gtk_radio_button_new_with_mnemonic (NULL, _("Ground"));
  gtk_widget_set_name (aref_ground, "aref_ground");
  gtk_widget_show (aref_ground);
  gtk_box_pack_start (GTK_BOX (hbox7), aref_ground, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (aref_ground), aref_ground_group);
  aref_ground_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (aref_ground));

  aref_diff = gtk_radio_button_new_with_mnemonic (NULL, _("Differential"));
  gtk_widget_set_name (aref_diff, "aref_diff");
  gtk_widget_show (aref_diff);
  gtk_box_pack_start (GTK_BOX (hbox7), aref_diff, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (aref_diff), aref_ground_group);
  aref_ground_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (aref_diff));

  aref_common = gtk_radio_button_new_with_mnemonic (NULL, _("Common"));
  gtk_widget_set_name (aref_common, "aref_common");
  gtk_widget_show (aref_common);
  gtk_box_pack_start (GTK_BOX (hbox7), aref_common, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (aref_common), aref_ground_group);
  aref_ground_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (aref_common));

  label29 = gtk_label_new (_("Buffer size (bytes):"));
  gtk_widget_set_name (label29, "label29");
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (option_table), label29, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label29), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox8, "hbox8");
  gtk_widget_show (hbox8);
  gtk_table_attach (GTK_TABLE (option_table), hbox8, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  bufsize_default = gtk_radio_button_new_with_mnemonic (NULL, _("Default"));
  gtk_widget_set_name (bufsize_default, "bufsize_default");
  gtk_widget_show (bufsize_default);
  gtk_box_pack_start (GTK_BOX (hbox8), bufsize_default, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (bufsize_default), bufsize_default_group);
  bufsize_default_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (bufsize_default));

  bufsize_custom = gtk_radio_button_new_with_mnemonic (NULL, _("Custom:"));
  gtk_widget_set_name (bufsize_custom, "bufsize_custom");
  gtk_widget_show (bufsize_custom);
  gtk_box_pack_start (GTK_BOX (hbox8), bufsize_custom, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (bufsize_custom), bufsize_default_group);
  bufsize_default_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (bufsize_custom));

  bufsize_entry = gtk_entry_new ();
  gtk_widget_set_name (bufsize_entry, "bufsize_entry");
  gtk_widget_show (bufsize_entry);
  gtk_box_pack_start (GTK_BOX (hbox8), bufsize_entry, TRUE, TRUE, 0);

  label30 = gtk_label_new (_("General"));
  gtk_widget_set_name (label30, "label30");
  gtk_widget_show (label30);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label30);
  gtk_label_set_justify (GTK_LABEL (label30), GTK_JUSTIFY_CENTER);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook2), empty_notebook_page);

  label31 = gtk_label_new (_("Channels"));
  gtk_widget_set_name (label31, "label31");
  gtk_widget_show (label31);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label31);
  gtk_label_set_justify (GTK_LABEL (label31), GTK_JUSTIFY_CENTER);

  dialog_action_area3 = GTK_DIALOG (comedi_dialog)->action_area;
  gtk_widget_set_name (dialog_action_area3, "dialog_action_area3");
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox2, "hbuttonbox2");
  gtk_widget_show (hbuttonbox2);
  gtk_container_add (GTK_CONTAINER (dialog_action_area3), hbuttonbox2);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox2), 8);

  button7 = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_set_name (button7, "button7");
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button7);
  GTK_WIDGET_SET_FLAGS (button7, GTK_CAN_DEFAULT);

  button8 = gtk_button_new_with_mnemonic (_("Apply"));
  gtk_widget_set_name (button8, "button8");
  gtk_widget_show (button8);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button8);
  GTK_WIDGET_SET_FLAGS (button8, GTK_CAN_DEFAULT);

  button9 = gtk_button_new_with_mnemonic (_("Cancel"));
  gtk_widget_set_name (button9, "button9");
  gtk_widget_show (button9);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button9);
  GTK_WIDGET_SET_FLAGS (button9, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) bufsize_default, "clicked",
                    G_CALLBACK (on_bufsize_default_clicked),
                    NULL);
  g_signal_connect ((gpointer) bufsize_custom, "clicked",
                    G_CALLBACK (on_bufsize_custom_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (comedi_on_ok),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (comedi_on_apply),
                    NULL);
  g_signal_connect_swapped ((gpointer) button9, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (comedi_dialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (comedi_dialog, comedi_dialog, "comedi_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (comedi_dialog, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (comedi_dialog, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (comedi_dialog, option_table, "option_table");
  GLADE_HOOKUP_OBJECT (comedi_dialog, device_label, "device_label");
  GLADE_HOOKUP_OBJECT (comedi_dialog, label26, "label26");
  GLADE_HOOKUP_OBJECT (comedi_dialog, device_entry, "device_entry");
  GLADE_HOOKUP_OBJECT (comedi_dialog, subdevice_optionmenu, "subdevice_optionmenu");
  GLADE_HOOKUP_OBJECT (comedi_dialog, convertwidget1, "convertwidget1");
  GLADE_HOOKUP_OBJECT (comedi_dialog, label28, "label28");
  GLADE_HOOKUP_OBJECT (comedi_dialog, rate_entry, "rate_entry");
  GLADE_HOOKUP_OBJECT (comedi_dialog, label27, "label27");
  GLADE_HOOKUP_OBJECT (comedi_dialog, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (comedi_dialog, aref_ground, "aref_ground");
  GLADE_HOOKUP_OBJECT (comedi_dialog, aref_diff, "aref_diff");
  GLADE_HOOKUP_OBJECT (comedi_dialog, aref_common, "aref_common");
  GLADE_HOOKUP_OBJECT (comedi_dialog, label29, "label29");
  GLADE_HOOKUP_OBJECT (comedi_dialog, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (comedi_dialog, bufsize_default, "bufsize_default");
  GLADE_HOOKUP_OBJECT (comedi_dialog, bufsize_custom, "bufsize_custom");
  GLADE_HOOKUP_OBJECT (comedi_dialog, bufsize_entry, "bufsize_entry");
  GLADE_HOOKUP_OBJECT (comedi_dialog, label30, "label30");
  GLADE_HOOKUP_OBJECT (comedi_dialog, label31, "label31");
  GLADE_HOOKUP_OBJECT_NO_REF (comedi_dialog, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (comedi_dialog, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (comedi_dialog, button7, "button7");
  GLADE_HOOKUP_OBJECT (comedi_dialog, button8, "button8");
  GLADE_HOOKUP_OBJECT (comedi_dialog, button9, "button9");

  return comedi_dialog;
}

