/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_comedi_dialog (void)
{
  GtkWidget *comedi_dialog;
  GtkWidget *dialog_vbox3;
  GtkWidget *notebook2;
  GtkWidget *option_table;
  GtkWidget *device_label;
  GtkWidget *label26;
  GtkWidget *device_entry;
  GtkWidget *subdevice_optionmenu;
  GtkWidget *subdevice_optionmenu_menu;
  GtkWidget *label28;
  GtkWidget *rate_entry;
  GtkWidget *label27;
  GtkWidget *hbox7;
  GSList *aref_group = NULL;
  GtkWidget *aref_ground;
  GtkWidget *aref_diff;
  GtkWidget *aref_common;
  GtkWidget *label29;
  GtkWidget *hbox8;
  GSList *buffer_size_group = NULL;
  GtkWidget *bufsize_default;
  GtkWidget *bufsize_custom;
  GtkWidget *bufsize_entry;
  GtkWidget *label30;
  GtkWidget *empty_notebook_page;
  GtkWidget *label31;
  GtkWidget *dialog_action_area3;
  GtkWidget *hbuttonbox2;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *button9;

  comedi_dialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (comedi_dialog), "comedi_dialog", comedi_dialog);
  gtk_window_set_title (GTK_WINDOW (comedi_dialog), "COMEDI Options");
  gtk_window_set_policy (GTK_WINDOW (comedi_dialog), TRUE, TRUE, FALSE);

  dialog_vbox3 = GTK_DIALOG (comedi_dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (comedi_dialog), "dialog_vbox3", dialog_vbox3);
  gtk_widget_show (dialog_vbox3);

  notebook2 = gtk_notebook_new ();
  gtk_widget_ref (notebook2);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "notebook2", notebook2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), notebook2, TRUE, TRUE, 0);

  option_table = gtk_table_new (5, 2, FALSE);
  gtk_widget_ref (option_table);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "option_table", option_table,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (option_table);
  gtk_container_add (GTK_CONTAINER (notebook2), option_table);
  gtk_container_set_border_width (GTK_CONTAINER (option_table), 10);
  gtk_table_set_row_spacings (GTK_TABLE (option_table), 10);
  gtk_table_set_col_spacings (GTK_TABLE (option_table), 10);

  device_label = gtk_label_new ("Device:");
  gtk_widget_ref (device_label);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "device_label", device_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (device_label);
  gtk_table_attach (GTK_TABLE (option_table), device_label, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (device_label), 0, 0.5);

  label26 = gtk_label_new ("Subdevice:");
  gtk_widget_ref (label26);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (option_table), label26, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  device_entry = gtk_entry_new ();
  gtk_widget_ref (device_entry);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "device_entry", device_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (device_entry);
  gtk_table_attach (GTK_TABLE (option_table), device_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  subdevice_optionmenu = gtk_option_menu_new ();
  gtk_widget_ref (subdevice_optionmenu);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "subdevice_optionmenu", subdevice_optionmenu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (subdevice_optionmenu);
  gtk_table_attach (GTK_TABLE (option_table), subdevice_optionmenu, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  subdevice_optionmenu_menu = gtk_menu_new ();
  gtk_option_menu_set_menu (GTK_OPTION_MENU (subdevice_optionmenu), subdevice_optionmenu_menu);

  label28 = gtk_label_new ("Sampling rate (Hz):");
  gtk_widget_ref (label28);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (option_table), label28, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  rate_entry = gtk_entry_new ();
  gtk_widget_ref (rate_entry);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "rate_entry", rate_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rate_entry);
  gtk_table_attach (GTK_TABLE (option_table), rate_entry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (0), 0, 0);

  label27 = gtk_label_new ("Analog reference:");
  gtk_widget_ref (label27);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (option_table), label27, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox7);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "hbox7", hbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox7);
  gtk_table_attach (GTK_TABLE (option_table), hbox7, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  aref_ground = gtk_radio_button_new_with_label (aref_group, "Ground");
  aref_group = gtk_radio_button_group (GTK_RADIO_BUTTON (aref_ground));
  gtk_widget_ref (aref_ground);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "aref_ground", aref_ground,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (aref_ground);
  gtk_box_pack_start (GTK_BOX (hbox7), aref_ground, FALSE, FALSE, 0);

  aref_diff = gtk_radio_button_new_with_label (aref_group, "Differential");
  aref_group = gtk_radio_button_group (GTK_RADIO_BUTTON (aref_diff));
  gtk_widget_ref (aref_diff);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "aref_diff", aref_diff,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (aref_diff);
  gtk_box_pack_start (GTK_BOX (hbox7), aref_diff, FALSE, FALSE, 0);

  aref_common = gtk_radio_button_new_with_label (aref_group, "Common");
  aref_group = gtk_radio_button_group (GTK_RADIO_BUTTON (aref_common));
  gtk_widget_ref (aref_common);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "aref_common", aref_common,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (aref_common);
  gtk_box_pack_start (GTK_BOX (hbox7), aref_common, FALSE, FALSE, 0);

  label29 = gtk_label_new ("Buffer size (bytes):");
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (option_table), label29, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox8);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox8);
  gtk_table_attach (GTK_TABLE (option_table), hbox8, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  bufsize_default = gtk_radio_button_new_with_label (buffer_size_group, "Default");
  buffer_size_group = gtk_radio_button_group (GTK_RADIO_BUTTON (bufsize_default));
  gtk_widget_ref (bufsize_default);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "bufsize_default", bufsize_default,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bufsize_default);
  gtk_box_pack_start (GTK_BOX (hbox8), bufsize_default, FALSE, FALSE, 0);

  bufsize_custom = gtk_radio_button_new_with_label (buffer_size_group, "Custom:");
  buffer_size_group = gtk_radio_button_group (GTK_RADIO_BUTTON (bufsize_custom));
  gtk_widget_ref (bufsize_custom);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "bufsize_custom", bufsize_custom,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bufsize_custom);
  gtk_box_pack_start (GTK_BOX (hbox8), bufsize_custom, FALSE, FALSE, 0);

  bufsize_entry = gtk_entry_new ();
  gtk_widget_ref (bufsize_entry);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "bufsize_entry", bufsize_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bufsize_entry);
  gtk_box_pack_start (GTK_BOX (hbox8), bufsize_entry, TRUE, TRUE, 0);

  label30 = gtk_label_new ("General");
  gtk_widget_ref (label30);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "label30", label30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label30);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label30);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook2), empty_notebook_page);

  label31 = gtk_label_new ("Channels");
  gtk_widget_ref (label31);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "label31", label31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label31);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label31);

  dialog_action_area3 = GTK_DIALOG (comedi_dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (comedi_dialog), "dialog_action_area3", dialog_action_area3);
  gtk_widget_show (dialog_action_area3);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area3), 10);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (dialog_action_area3), hbuttonbox2, TRUE, TRUE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox2), 8);

  button7 = gtk_button_new_with_label ("OK");
  gtk_widget_ref (button7);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "button7", button7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button7);
  GTK_WIDGET_SET_FLAGS (button7, GTK_CAN_DEFAULT);

  button8 = gtk_button_new_with_label ("Apply");
  gtk_widget_ref (button8);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "button8", button8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button8);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button8);
  GTK_WIDGET_SET_FLAGS (button8, GTK_CAN_DEFAULT);

  button9 = gtk_button_new_with_label ("Cancel");
  gtk_widget_ref (button9);
  gtk_object_set_data_full (GTK_OBJECT (comedi_dialog), "button9", button9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button9);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button9);
  GTK_WIDGET_SET_FLAGS (button9, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (bufsize_default), "clicked",
                      GTK_SIGNAL_FUNC (on_bufsize_default_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bufsize_custom), "clicked",
                      GTK_SIGNAL_FUNC (on_bufsize_custom_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button7), "clicked",
                      GTK_SIGNAL_FUNC (comedi_on_ok),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button8), "clicked",
                      GTK_SIGNAL_FUNC (comedi_on_apply),
                      NULL);
  gtk_signal_connect_object (GTK_OBJECT (button9), "clicked",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (comedi_dialog));

  return comedi_dialog;
}

