/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_dialog2 (void)
{
  GtkWidget *dialog2;
  GtkWidget *dialog_vbox1;
  GtkWidget *notebook1;
  GtkWidget *table1;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label10;
  GtkWidget *vbox1;
  GSList *vbox1_group = NULL;
  GtkWidget *radiobutton12;
  GtkWidget *radiobutton13;
  GtkWidget *vbox2;
  GSList *vbox2_group = NULL;
  GtkWidget *radiobutton14;
  GtkWidget *radiobutton15;
  GtkWidget *radiobutton16;
  GtkWidget *radiobutton17;
  GtkWidget *vbox3;
  GSList *vbox3_group = NULL;
  GtkWidget *radiobutton18;
  GtkWidget *radiobutton19;
  GtkWidget *vbox4;
  GSList *vbox4_group = NULL;
  GtkWidget *radiobutton20;
  GtkWidget *radiobutton21;
  GtkWidget *radiobutton22;
  GtkWidget *radiobutton23;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton3;
  GtkWidget *hbox1;
  GSList *hbox1_group = NULL;
  GtkWidget *radiobutton24;
  GtkWidget *radiobutton25;
  GtkWidget *label11;
  GtkWidget *hseparator3;
  GtkWidget *hseparator2;
  GtkWidget *hseparator1;
  GtkWidget *vseparator1;
  GtkWidget *vseparator2;
  GtkWidget *label3;
  GtkWidget *table2;
  GtkWidget *label12;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *hbox4;
  GSList *hbox4_group = NULL;
  GtkWidget *radiobutton30;
  GtkWidget *radiobutton31;
  GtkWidget *hbox5;
  GSList *hbox5_group = NULL;
  GtkWidget *radiobutton38;
  GtkWidget *radiobutton40;
  GtkWidget *label15;
  GtkWidget *entry1;
  GtkWidget *hseparator4;
  GtkWidget *hseparator5;
  GtkWidget *label21;
  GtkWidget *label19;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *vseparator3;
  GtkWidget *hscale1;
  GtkWidget *hscale2;
  GtkWidget *hbox3;
  GSList *hbox3_group = NULL;
  GtkWidget *radiobutton28;
  GtkWidget *radiobutton39;
  GtkWidget *label4;
  GtkWidget *empty_notebook_page;
  GtkWidget *label5;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkWidget *button3;

  dialog2 = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (dialog2), "dialog2", dialog2);
  gtk_window_set_title (GTK_WINDOW (dialog2), "BitScope");

  dialog_vbox1 = GTK_DIALOG (dialog2)->vbox;
  gtk_object_set_data (GTK_OBJECT (dialog2), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), notebook1, TRUE, TRUE, 0);

  table1 = gtk_table_new (7, 5, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (notebook1), table1);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 10);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 10);

  label6 = gtk_label_new ("X (Primary)");
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label7 = gtk_label_new ("Y (Secondary)");
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 4, 5, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label8 = gtk_label_new ("Source\nChannel");
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table1), label8, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label10 = gtk_label_new ("Input\nVoltage\nRange");
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 0, 1, 6, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_table_attach (GTK_TABLE (table1), vbox1, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  radiobutton12 = gtk_radio_button_new_with_label (vbox1_group, "A");
  vbox1_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton12));
  gtk_widget_ref (radiobutton12);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton12", radiobutton12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton12);
  gtk_box_pack_start (GTK_BOX (vbox1), radiobutton12, FALSE, FALSE, 0);

  radiobutton13 = gtk_radio_button_new_with_label (vbox1_group, "B");
  vbox1_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton13));
  gtk_widget_ref (radiobutton13);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton13", radiobutton13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton13);
  gtk_box_pack_start (GTK_BOX (vbox1), radiobutton13, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton13), TRUE);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_table_attach (GTK_TABLE (table1), vbox2, 4, 5, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  radiobutton14 = gtk_radio_button_new_with_label (vbox2_group, "1.30V");
  vbox2_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton14));
  gtk_widget_ref (radiobutton14);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton14", radiobutton14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton14);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton14, FALSE, FALSE, 0);

  radiobutton15 = gtk_radio_button_new_with_label (vbox2_group, "6.00V");
  vbox2_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton15));
  gtk_widget_ref (radiobutton15);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton15", radiobutton15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton15);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton15, FALSE, FALSE, 0);

  radiobutton16 = gtk_radio_button_new_with_label (vbox2_group, "12.0V");
  vbox2_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton16));
  gtk_widget_ref (radiobutton16);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton16", radiobutton16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton16);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton16, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton16), TRUE);

  radiobutton17 = gtk_radio_button_new_with_label (vbox2_group, "+/- 31.60 V");
  vbox2_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton17));
  gtk_widget_ref (radiobutton17);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton17", radiobutton17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton17);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton17, FALSE, FALSE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_table_attach (GTK_TABLE (table1), vbox3, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  radiobutton18 = gtk_radio_button_new_with_label (vbox3_group, "A");
  vbox3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton18));
  gtk_widget_ref (radiobutton18);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton18", radiobutton18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton18);
  gtk_box_pack_start (GTK_BOX (vbox3), radiobutton18, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton18), TRUE);

  radiobutton19 = gtk_radio_button_new_with_label (vbox3_group, "B");
  vbox3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton19));
  gtk_widget_ref (radiobutton19);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton19", radiobutton19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton19);
  gtk_box_pack_start (GTK_BOX (vbox3), radiobutton19, FALSE, FALSE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_table_attach (GTK_TABLE (table1), vbox4, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  radiobutton20 = gtk_radio_button_new_with_label (vbox4_group, "+/- 0.632 V");
  vbox4_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton20));
  gtk_widget_ref (radiobutton20);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton20", radiobutton20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton20);
  gtk_box_pack_start (GTK_BOX (vbox4), radiobutton20, FALSE, FALSE, 0);

  radiobutton21 = gtk_radio_button_new_with_label (vbox4_group, "6.00V");
  vbox4_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton21));
  gtk_widget_ref (radiobutton21);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton21", radiobutton21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton21);
  gtk_box_pack_start (GTK_BOX (vbox4), radiobutton21, FALSE, FALSE, 0);

  radiobutton22 = gtk_radio_button_new_with_label (vbox4_group, "12.0V");
  vbox4_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton22));
  gtk_widget_ref (radiobutton22);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton22", radiobutton22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton22);
  gtk_box_pack_start (GTK_BOX (vbox4), radiobutton22, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton22), TRUE);

  radiobutton23 = gtk_radio_button_new_with_label (vbox4_group, "+/- 31.60 V");
  vbox4_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton23));
  gtk_widget_ref (radiobutton23);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton23", radiobutton23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton23);
  gtk_box_pack_start (GTK_BOX (vbox4), radiobutton23, FALSE, FALSE, 0);

  checkbutton2 = gtk_check_button_new_with_label ("x10");
  gtk_widget_ref (checkbutton2);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "checkbutton2", checkbutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton2);
  gtk_table_attach (GTK_TABLE (table1), checkbutton2, 2, 3, 4, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton2), TRUE);

  checkbutton3 = gtk_check_button_new_with_label ("x10");
  gtk_widget_ref (checkbutton3);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "checkbutton3", checkbutton3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton3);
  gtk_table_attach (GTK_TABLE (table1), checkbutton3, 4, 5, 4, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton3), TRUE);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_table_attach (GTK_TABLE (table1), hbox1, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  radiobutton24 = gtk_radio_button_new_with_label (hbox1_group, "POD");
  hbox1_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton24));
  gtk_widget_ref (radiobutton24);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton24", radiobutton24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton24);
  gtk_box_pack_start (GTK_BOX (hbox1), radiobutton24, FALSE, FALSE, 0);

  radiobutton25 = gtk_radio_button_new_with_label (hbox1_group, "BNC");
  hbox1_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton25));
  gtk_widget_ref (radiobutton25);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton25", radiobutton25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton25);
  gtk_box_pack_start (GTK_BOX (hbox1), radiobutton25, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton25), TRUE);

  label11 = gtk_label_new ("");
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table1), label11, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator3);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "hseparator3", hseparator3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator3);
  gtk_table_attach (GTK_TABLE (table1), hseparator3, 0, 5, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator2);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "hseparator2", hseparator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator2);
  gtk_table_attach (GTK_TABLE (table1), hseparator2, 0, 5, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_table_attach (GTK_TABLE (table1), hseparator1, 0, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_ref (vseparator1);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "vseparator1", vseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator1);
  gtk_table_attach (GTK_TABLE (table1), vseparator1, 1, 2, 0, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_ref (vseparator2);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "vseparator2", vseparator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator2);
  gtk_table_attach (GTK_TABLE (table1), vseparator2, 3, 4, 0, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label3 = gtk_label_new ("Input");
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label3);

  table2 = gtk_table_new (10, 3, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (notebook1), table2);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 10);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 10);

  label12 = gtk_label_new ("Trigger Condition");
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table2), label12, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label16 = gtk_label_new ("Edge Sense");
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table2), label16, 0, 1, 9, 10,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label17 = gtk_label_new ("Trigger Source");
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table2), label17, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_table_attach (GTK_TABLE (table2), hbox4, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  radiobutton30 = gtk_radio_button_new_with_label (hbox4_group, "Digital");
  hbox4_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton30));
  gtk_widget_ref (radiobutton30);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton30", radiobutton30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton30);
  gtk_box_pack_start (GTK_BOX (hbox4), radiobutton30, FALSE, FALSE, 0);

  radiobutton31 = gtk_radio_button_new_with_label (hbox4_group, "Analog");
  hbox4_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton31));
  gtk_widget_ref (radiobutton31);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton31", radiobutton31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton31);
  gtk_box_pack_start (GTK_BOX (hbox4), radiobutton31, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton31), TRUE);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_table_attach (GTK_TABLE (table2), hbox5, 2, 3, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  radiobutton38 = gtk_radio_button_new_with_label (hbox5_group, "Level");
  hbox5_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton38));
  gtk_widget_ref (radiobutton38);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton38", radiobutton38,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton38);
  gtk_box_pack_start (GTK_BOX (hbox5), radiobutton38, FALSE, FALSE, 0);

  radiobutton40 = gtk_radio_button_new_with_label (hbox5_group, "Edge");
  hbox5_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton40));
  gtk_widget_ref (radiobutton40);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton40", radiobutton40,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton40);
  gtk_box_pack_start (GTK_BOX (hbox5), radiobutton40, FALSE, FALSE, 0);

  label15 = gtk_label_new ("Sensitivity");
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table2), label15, 0, 1, 8, 9,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_table_attach (GTK_TABLE (table2), entry1, 2, 3, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (entry1), "1000XXXX");

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator4);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "hseparator4", hseparator4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator4);
  gtk_table_attach (GTK_TABLE (table2), hseparator4, 0, 3, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator5);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "hseparator5", hseparator5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator5);
  gtk_table_attach (GTK_TABLE (table2), hseparator5, 0, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label21 = gtk_label_new ("16");
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table2), label21, 2, 3, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label19 = gtk_label_new ("128");
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table2), label19, 2, 3, 5, 6,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label13 = gtk_label_new ("Analog Levels");
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table2), label13, 0, 1, 3, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label14 = gtk_label_new ("Level Selection");
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table2), label14, 0, 1, 5, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  vseparator3 = gtk_vseparator_new ();
  gtk_widget_ref (vseparator3);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "vseparator3", vseparator3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator3);
  gtk_table_attach (GTK_TABLE (table2), vseparator3, 1, 2, 0, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hscale1 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (4, -1, 8, 1, 1, 0)));
  gtk_widget_ref (hscale1);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "hscale1", hscale1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hscale1);
  gtk_table_attach (GTK_TABLE (table2), hscale1, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_draw_value (GTK_SCALE (hscale1), FALSE);
  gtk_scale_set_digits (GTK_SCALE (hscale1), 0);

  hscale2 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (128, 0, 255, 1, 1, 0)));
  gtk_widget_ref (hscale2);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "hscale2", hscale2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hscale2);
  gtk_table_attach (GTK_TABLE (table2), hscale2, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_usize (hscale2, 256, -2);
  gtk_scale_set_draw_value (GTK_SCALE (hscale2), FALSE);
  gtk_scale_set_digits (GTK_SCALE (hscale2), 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_table_attach (GTK_TABLE (table2), hbox3, 2, 3, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  radiobutton28 = gtk_radio_button_new_with_label (hbox3_group, "F->T");
  hbox3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton28));
  gtk_widget_ref (radiobutton28);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton28", radiobutton28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton28);
  gtk_box_pack_start (GTK_BOX (hbox3), radiobutton28, FALSE, FALSE, 0);

  radiobutton39 = gtk_radio_button_new_with_label (hbox3_group, "T->F");
  hbox3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton39));
  gtk_widget_ref (radiobutton39);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "radiobutton39", radiobutton39,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton39);
  gtk_box_pack_start (GTK_BOX (hbox3), radiobutton39, FALSE, FALSE, 0);

  label4 = gtk_label_new ("Trigger");
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label4);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label5 = gtk_label_new ("Time");
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label5);

  dialog_action_area1 = GTK_DIALOG (dialog2)->action_area;
  gtk_object_set_data (GTK_OBJECT (dialog2), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, FALSE, FALSE, 0);

  button1 = gtk_button_new_with_label ("OK");
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  button2 = gtk_button_new_with_label ("Apply");
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  button3 = gtk_button_new_with_label ("Cancel");
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (dialog2), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (dialog2), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (dialog2), "destroy_event",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (notebook1), "switch_page",
                      GTK_SIGNAL_FUNC (on_notebook1_switch_page),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton14), "toggled",
                      GTK_SIGNAL_FUNC (on_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton15), "toggled",
                      GTK_SIGNAL_FUNC (on_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton16), "toggled",
                      GTK_SIGNAL_FUNC (on_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton17), "toggled",
                      GTK_SIGNAL_FUNC (on_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton20), "toggled",
                      GTK_SIGNAL_FUNC (on_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton21), "toggled",
                      GTK_SIGNAL_FUNC (on_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton22), "toggled",
                      GTK_SIGNAL_FUNC (on_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton23), "toggled",
                      GTK_SIGNAL_FUNC (on_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton2), "toggled",
                      GTK_SIGNAL_FUNC (on_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton3), "toggled",
                      GTK_SIGNAL_FUNC (on_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton24), "toggled",
                      GTK_SIGNAL_FUNC (on_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton25), "toggled",
                      GTK_SIGNAL_FUNC (on_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry1), "activate",
                      GTK_SIGNAL_FUNC (on_entry1_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_ok),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (on_apply),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);

  return dialog2;
}

